= Asciidoc vers HTML


== Docker

https://hub.docker.com/r/asciidoctor/docker-asciidoctor/[]

.Comment utiliser l'image Docker
----
docker run -it -v <your directory>:/documents/ asciidoctor/docker-asciidoctor
asciidoctor sample.adoc
----

== Asciidoctorj

https://github.com/asciidoctor/asciidoctorj[]

.Comment utiliser asciidoctorj
----
Linux: asciidoctorj-2.5.7/bin/asciidoctorj README.adoc
Windows: asciidoctorj-2.5.7\bin\asciidoctorj.bat README.adoc
----

== Maven

https://sfauvel.github.io/documentationtesting/documentationtesting/org/sfvl/howto/Tutorial.html#_convert_to_html[]

== IDE

* Intellij
** Allez sur la fichier asciidoc.
** Cliquez sur `HTML`
* VSCode
** Ouvrez la palette de commandes (CTRL + SHIFT + 'P') et choisissez `Asciidoc: Save HTML Document` (CTRL + ALT + 'S')

== Github

Nous utilisons l'action Github https://github.com/manoelcampos/asciidoctor-ghpages-action[asciidoctor-ghpages-action].

=== Configurer Github

// tag::github-configure[]
L'action que nous utilisons va créer une branche.
Il est donc nécessaire de lui donner des droits d'écriture sur le dépot.

====
Allez dans `Settings > Actions > General > Workflow permissions` et autorisez les workflows à écrire sur le dépot.

* [x] Workflows have read and write permissions in the repository for all scopes.
* [ ] Workflows have read permissions in the repository for the contents and packages scopes only.
====
// end::github-configure[]

=== Créer l'action

// tag::github-create-action[]
Nous allons ajouter une action qui créé les fichiers HTML à partir des fichier asciidoc.
Ils seront alors commités dans la branche `gh-pages`.

Si vous clonez le dépot https://github.com/sfauvel/Parrot-Refactoring-Kata[], 
vous trouverez le fichier `.github/workflows/publish_site.yaml` qui configure l'action pour publier le site.
Vous aurez juste à configurer le chemin vers le répertoire où se trouve votre documentation.
Nous vous suggérons de la mettre dans un répertoire `docs`.
Vous devez avoir un fichier `README.adoc` dans le répertoire.
Il deviendra le fichier `index.html` de votre site.

Si vous utilisez votre propre projet, créez, dans le répertoire `.github/workflows`, le fichier `publish_site.yaml` avec le code suivant et configurez correctement le répertoire de sources.

.Publish action
====
[source,yaml]
----
name: GitHub Pages Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      
    # Includes the AsciiDoctor GitHub Pages Action to convert adoc files to html and publish to gh-pages branch
    # from https://github.com/manoelcampos/asciidoctor-ghpages-action
    - name: asciidoctor-ghpages
      uses: manoelcampos/asciidoctor-ghpages-action@v2
      with:
        pdf_build: true
        asciidoctor_params: --attribute=htmlformat
        #asciidoctor_params: --attribute=nofooter --attribute=htmlformat
        # adoc_file_ext: .ascii # default is .adoc
        source_dir: pages/ # default is .
        # slides_build: true
        # pre_build: python pre_build.py
        # post_build:
----
====
// end::github-create-action[]

=== Publish the site

// tag::github-publish[]
Une fois la branche créée, nous pouvons publier son contenu.
Pour cela, allez dans : `Settings > Pages > Branch`
et choisissez `gh-pages`.

Votre page sera alors visible depuis l'URL: `https://[github account].github.io/[repository]/`.

Exemple: https://sfauvel.github.io/doc_as_test_workshop/

Le site sera mis à jour à chaque commit sur votre branche `main`. 
Cela prend généralement 1mn avant de pouvoir consulter le résultat sur votre site publique.
// end::github-publish[]