
ifndef::htmlformat[]
:page_extension: adoc
endif::[]

ifdef::htmlformat[]
:page_extension: html
endif::[]

= Asciidoc

Vous pouvez voir le code source utilisé pour afficher cette page à l'adresse suivante: link:asciidoc_source.{page_extension}[Asciidoc source]

Nous utilisons le format `asciidoc` pour écrirte notre documentation.

Cette section permet de vous familiariser avec ce format.
Elle explique les principales syntaxes nécessaires dans notre contexts.

Si vous voulez allez plus loin, vous pouvez consulter les documenations suivantes : 
https://docs.asciidoctor.org/asciidoctor/latest/[]

https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/[]


Vous pouvez écrire en *gras* ou en _italique_.

---

* Faire
* des
* listes
* à
* puces

---

.Exemple de tableau avec en-tête
[%autowidth]
|====
| Table | Header

| Line 1 | Value
| Line 2 | Value
|====

---

Vous pouvez inclure d'autre fichiers.

include::text.adoc[]

---

On peut afficher des caractères spéciaux: &#x21E6; &#x21E7; &#x21E8; &#x21E9; 

---

.Image
image:asciidoctor-logo.svg[width=100px]

---

.Code source
[source, java]
----
/**
* Code avec highlighter.
*/
public class OperationsTest {
    @Test
    public void calculate_the_square_of_a_number() {
        assertEquals(42, Math.max(42, 35));
    }
}
----

___

.Example d'inclusion de SVG
++++
<svg width=300 height=100  style="background-color:#b8d6ea">
    <rect x="40" y="10" width="40" height="40" fill="green"></rect>
    
    <text x="45" y="25">Text</text>

    <circle cx="80" cy="60" r="20" fill="red"></circle>

    <polyline style="stroke:blue;fill:none;stroke-width:3" points="
        20,50
        80,60
        100,45
        120,55
    "/>
</svg>
++++
